#Spring Security code
spring:
 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: https://1authority-interns.1rivet.com:5004
     jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
     audiences: DeskBookApi

#Database Connection code
 datasource:
  url: jdbc:sqlserver://localhost:1433;database=DeskBookDev;encrypt=true;trustServerCertificate=true;
  username: sa
  password: Admin@123
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: validate
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
server:
   port: 9443